name: CI

on: [push, pull_request]

jobs:
  script-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    name: Test Utilities - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}  
      run: conda env update --file script-environment.yml --name test
    - name: Run tests
      shell: bash -l {0}  
      run: python -m pytest -v -s utils/tests
  notebook-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        notebook-dir: [AOI Generation, CEO Post Processing, CEO GO Join, CEO Project Generation]
    name: Test - ${{ matrix.os }}, ${{ matrix.notebook-dir }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge, defaults
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}  
      run:
        conda env update --file "${{ matrix.notebook-dir }}/environment.yml" --name test
    - name: Install Pytest Dependencies
      shell: bash -l {0}  
      run: |
        conda install -c anaconda pytest
        conda install -c conda-forge nbmake
    - name: Run Pytest
      shell: bash -l {0}    
      run: python -m pytest -vv --nbmake "./${{ matrix.notebook-dir }}"
  colab-test:
    strategy:
      fail-fast: false
      matrix:
        notebook-dir: [AOI Generation, CEO GO Join, CEO Post Processing]
    name: Colab Test - ${{ matrix.notebook-dir }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge, defaults
        auto-update-conda: true
        python-version: 3.7
    - name: Install dependencies
      run: conda env update --file "${{ matrix.notebook-dir }}/environment.yml" --name test
    - name: Install Pytest Dependencies
      shell: bash -l {0}
      run: |
        conda install -c anaconda pytest
        conda install -c conda-forge nbmake
    - name: Set Mock Colab Environmental Variabe
      shell: bash -l {0}
      run: conda env config vars set MOCK_COLAB=true
    - name: Run Pytest
      shell: bash -l {0}
      run: python -m pytest -vv --nbmake "./${{ matrix.notebook-dir }}"